name: Kafka-Spark-Timescale Pipeline

on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose up -d --build

    - name: Wait for Kafka and Timescale to be ready
      run: sleep 30

    - name: Run Producer to send data to Kafka
      run: docker-compose run --rm producer

    - name: Run Spark job to process data
      run: docker-compose run --rm spark_stream

    - name: Dump TimescaleDB data to CSV
      run: |
        docker exec timescaledb psql -U myuser -d mydb -c "\COPY sensor_data TO '/tmp/sensor_data.csv' CSV HEADER"
        docker cp timescaledb:/tmp/sensor_data.csv ./sensor_data.csv

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sensor-data
        path: sensor_data.csv
